[tool.black]
line-length = 88
target-version = ['py312']
exclude = "alembic"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = "-q"
